### ISSUE TITLE
че делать?(термукс)

### ISSUE THREAD

**Issue by 99zxcaworu15** [pixxxionix/satoshi#1]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/satoshi/satoshi.py", line 58644, in <module>
    import configs
  File "/data/data/com.termux/files/home/satoshi/configs.py", line 15626, in <module>
    from movefile import banner_menu
  File "/data/data/com.termux/files/home/satoshi/movefile.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by iwantodietonight** [comment]
<function banner at 0x7cd453e020>

**Comment by 99zxcaworu15** [comment]
> <function banner at 0x7cd453e020>
> 

?

**Comment by iwantodietonight** [comment]
че делать/у мя траблы

**Comment by 99zxcaworu15** [comment]
> че делать/у мя траблы
> 

?

**Comment by hnuzik** [comment]
> <function banner at 0x7cd453e020>
жиза, помогите че делать

**Comment by SKLINCE** [comment]
![Screenshot_2023-09-27-09-25-02-94](https://github.com/pixxxionix/satoshi/assets/145360385/2b90324d-426d-417d-ab98-8def7072b495)
Ошибка

**Comment by hnuzik** [comment]
дак открывай HE satoshi.p a satoshi.py

**Comment by GONNORRHEA** [comment]
> дак открывай HE satoshi.p a satoshi.py

У мя траблы 402 ошибка

**Comment by Zavertin-beep** [comment]
<function banner at 0x7cd453e020> ошибка че делать

**Comment by pixxxionix** [comment]
да вы тупые сука, там все написано

**Comment by Zavertin-beep** [comment]
Чего блять

сб, 16 нояб. 2024 г., 00:02 pixxxionix ***@***.***>:
