### ISSUE TITLE
Термукс как пофиксить

### ISSUE THREAD

**Issue by gwer7272** [pixxxionix/satoshi#3]
Помогите плс что делать не знаю
![Uploading Screenshot_2023-10-08-20-57-47-245_com.termux.jpg…]()

**Comment by gwer7272** [comment]
Теперь это выдает
![Uploading Screenshot_2023-10-08-21-03-49-167_com.termux.jpg…]()

**Comment by gwer7272** [comment]
Код такой
![Uploading Screenshot_2023-10-08-21-04-51-559_com.termux.png…]()

**Comment by gwer7272** [comment]
Проблему с запуском я решил
Но что делать с этим![Screenshot_2023-10-08-22-14-25-692_com.termux.png](https://github.com/pixxxionix/satoshi/assets/147339992/ede16674-8037-4e6f-8d95-348b646dc4c1)

**Comment by k1sel807** [comment]
бро, пофиксил?

**Comment by gwer7272** [comment]
Нет

**Comment by asmoil** [comment]
![Screenshot_20241024_110957_Termux](https://github.com/user-attachments/assets/2e0e9afd-3772-4825-af08-5a65d0b1f71e)
помогите решить ошибку

**Comment by pixxxionix** [comment]
эта функция изначально не работала
