### ISSUE TITLE
Помогите с сатоши

### ISSUE THREAD

**Issue by welumv** [pixxxionix/satoshi#5]
![Screenshot_20240618_181627](https://github.com/pixxxionix/satoshi/assets/173179835/d844960d-fd8f-4d59-875f-d3e7f8169840)

**Comment by welumv** [comment]
После этого не качается

**Comment by Itanami-gh** [comment]
Перед тем как юзать git clone "ссылка ", используй команду pkg install git

**Comment by Itanami-gh** [comment]
У меня такая же проблема была, нужно было просто скачать git
